HWBudgetTrackerV1/Models/FinancialAccounts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HWBudgetTrackerV1.Models
{
    public class FinancialAccounts
    {
        public FinancialAccounts()
        {
            this.Transactions = new HashSet<Transaction>();
        }
        public int Id { get; set; }
        [Display(Name = "Bank Account Name")]
        public string Name { get; set; }
        [Display(Name = "Bank Account Balance")]
        public int Balance { get; set; }
        public int ReconciledBalance { get; set; }

        public int HouseholdId { get; set; }
        public int TransactionId { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Household Household { get; set; }


    }
}

HWBudgetTrackerV1/Controllers/FinancialAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HWBudgetTrackerV1.Models;
using Microsoft.AspNet.Identity;

namespace HWBudgetTrackerV1.Controllers
{
    public class FinancialAccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FinancialAccounts
        [Authorize]
        public ActionResult Index(int? householdId)
        {
            //var thisuser = db.Users.Find(User.Identity.GetUserId());
            var financialAccounts = db.FinancialAccounts.Where(h => h.HouseholdId == householdId).Include(f => f.Household);
            return View(financialAccounts.ToList());
        }

        // GET: FinancialAccounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FinancialAccounts financialAccounts = db.FinancialAccounts.Find(id);
            if (financialAccounts == null)
            {
                return HttpNotFound();
            }
            //update account balance by summing all transactions for that account
            List<Transaction> AddUp = db.FinancialAccounts.SelectMany(t => t.Transactions).ToList();
            var AddAccounts = db.Transactions.Where(m => m.FinancialAccountsId == id).ToList();
            var runningTotal = 0;

            foreach (var usr in AddAccounts)
            {
                runningTotal += usr.Amount;
                //UsersViewModel vm = new UsersViewModel();
                //vm.User = usr;
                //vm.Roles = helper.ListUserRoles(usr.Id).ToList();
                //users.Add(vm);
                
            }
            financialAccounts.Balance = runningTotal;

            db.Entry(financialAccounts).State = EntityState.Modified;
            db.SaveChanges();

            return View(financialAccounts);
        }

        // GET: FinancialAccounts/Create
        public ActionResult Create(int HouseholdId)
        {
            FinancialAccounts financialAccount = new FinancialAccounts();
            financialAccount.HouseholdId = HouseholdId;

            //ViewBag.HouseholdId = new SelectList(db.Households, "Id", "Name");
            return View(financialAccount);
        }

        // POST: FinancialAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Balance,ReconciledBalance,HouseholdId,TransactionId")] FinancialAccounts financialAccounts)
        {
            if (ModelState.IsValid)
            {
                db.FinancialAccounts.Add(financialAccounts);
                db.SaveChanges();
                return RedirectToAction("Details", "Households", new { id = financialAccounts.HouseholdId });
               // return RedirectToAction("Index");

            }

            ViewBag.HouseholdId = new SelectList(db.Households, "Id", "Name", financialAccounts.HouseholdId);
            return View(financialAccounts);
        }

        // GET: FinancialAccounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FinancialAccounts financialAccounts = db.FinancialAccounts.Find(id);
            if (financialAccounts == null)
            {
                return HttpNotFound();
            }
            ViewBag.HouseholdId = new SelectList(db.Households, "Id", "Name", financialAccounts.HouseholdId);
            return View(financialAccounts);
        }

        // POST: FinancialAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Balance,ReconciledBalance,HouseholdId,TransactionId")] FinancialAccounts financialAccounts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(financialAccounts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HouseholdId = new SelectList(db.Households, "Id", "Name", financialAccounts.HouseholdId);
            return View(financialAccounts);
        }

        // GET: FinancialAccounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FinancialAccounts financialAccounts = db.FinancialAccounts.Find(id);
            if (financialAccounts == null)
            {
                return HttpNotFound();
            }
            return View(financialAccounts);
        }

        // POST: FinancialAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FinancialAccounts financialAccounts = db.FinancialAccounts.Find(id);
            db.FinancialAccounts.Remove(financialAccounts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HWBudgetTrackerV1/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HWBudgetTrackerV1.Models;

namespace HWBudgetTrackerV1.Controllers
{
    public class TransactionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transactions
        public ActionResult Index()
        {
            var transactions = db.Transactions.Include(t => t.Category).Include(t => t.EnteredBy);
            return View(transactions.ToList());
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: Transactions/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            ViewBag.EnteredById = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,Date,Amount,Type,Reconciled,ReconciledAmount,FinancialAccountsId,CategoryId,EnteredById")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
               // return RedirectToAction("Index");
                return RedirectToAction("Details", "FinancialAccounts", new { Id = transaction.FinancialAccountsId });

            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", transaction.CategoryId);
            ViewBag.EnteredById = new SelectList(db.Users, "Id", "FirstName", transaction.EnteredById);
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", transaction.CategoryId);
            ViewBag.EnteredById = new SelectList(db.Users, "Id", "FirstName", transaction.EnteredById);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Date,Amount,Type,Reconciled,ReconciledAmount,AccountId,CategoryId,EnteredById")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", transaction.CategoryId);
            ViewBag.EnteredById = new SelectList(db.Users, "Id", "FirstName", transaction.EnteredById);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transaction transaction = db.Transactions.Find(id);
            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HWBudgetTrackerV1/Views/FinancialAccounts/Create.cshtml
@model HWBudgetTrackerV1.Models.FinancialAccounts

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
 
    <div class="form-horizontal">
        <h4>FinancialAccounts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReconciledBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReconciledBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReconciledBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdId, "HouseholdId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("HouseholdId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HouseholdId, "", new { @class = "text-danger" })*@
                @Html.DisplayFor(model => model.HouseholdId)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TransactionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransactionId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
    @Html.ActionLink("return to Accounts View", "Index", "FinancialAccounts", new { householdId = Model.HouseholdId}, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HWBudgetTrackerV1/Views/FinancialAccounts/Delete.cshtml
@model HWBudgetTrackerV1.Models.FinancialAccounts

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FinancialAccounts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Household.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Household.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReconciledBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReconciledBalance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransactionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HWBudgetTrackerV1/Views/FinancialAccounts/Details.cshtml
@model HWBudgetTrackerV1.Models.FinancialAccounts

@{
    ViewBag.Title = "Financial Account Details";
}

<h2>Details</h2>

<div>
    <h4>FinancialAccounts and Transactions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Household.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Household.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReconciledBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReconciledBalance)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.TransactionId)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.TransactionId)
        </dd>*@

    </dl>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().Reconciled)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().ReconciledAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().FinancialAccountsId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().CategoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().EnteredById)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transactions.FirstOrDefault().Amount)
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Transactions.Count() == 0)
            {
            <tr>
                <td>
                </td>
                <td>
                    No Transactions yet, feel free to add some.
                    @Model.Transactions.Count()
                </td>
            </tr>
        }
        @foreach (var item in Model.Transactions)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FinancialAccountsId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reconciled)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReconciledAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FinancialAccountsId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EnteredBy.DisplayName)
                </td>




                <td>
                    <div> @Html.ActionLink("Transaction Details", "Details", "Transactions", new { id = item.Id }, null)|</div>
                    <div>
                        @Html.ActionLink("Edit Transaction ", "Edit", "Transactions", new { id = item.Id }, null) |
                    </div>
                    <div>
                        @Html.ActionLink("Delete Transaction", "Delete", "Transactions", new { id = item.Id }, null)
                    </div>
                </td>
            </tr>
        }



    </tbody>
</table>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
    @Html.ActionLink("Add a Transaction", "Create", "Transactions", new { FinancialAccountsId = Model.Id }, null) I

</p>

HWBudgetTrackerV1/Views/FinancialAccounts/Edit.cshtml
@model HWBudgetTrackerV1.Models.FinancialAccounts

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FinancialAccounts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReconciledBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReconciledBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReconciledBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdId, "HouseholdId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HouseholdId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HouseholdId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransactionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransactionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HWBudgetTrackerV1/Views/FinancialAccounts/Index.cshtml
@model IEnumerable<HWBudgetTrackerV1.Models.FinancialAccounts>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Household.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReconciledBalance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Household.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReconciledBalance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransactionId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>